### Подтягиваем библиотеки

In [1]:
import PrepData as prd
import numpy as np

from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

### Создаем входные данные

#### Массивы

In [2]:
GOOD_dataFrame = np.array([[1.0, 1.0, 1.0],
                           [1.0, 1.0, 1.0],
                           [1.0, 1.0, 1.0]])

BAD_dataFrame  = np.array([[np.nan, np.nan, np.nan],
                           [1,      1,      1],
                           [1,      1,      np.nan,]])

BAD_dataFrame

array([[nan, nan, nan],
       [ 1.,  1.,  1.],
       [ 1.,  1., nan]])

#### Pipelines

In [3]:
prepData = prd.PrepData()

simple_inputer = KNNImputer(n_neighbors = 2)
std_scaler = StandardScaler()

pipeline = Pipeline([('imputer', simple_inputer),('scaler', std_scaler)])

Create pipline successfull


#### Наконец тесты

#### add_col_indexes

In [4]:
print(BAD_dataFrame)
print(prepData.add_col_indexes(BAD_dataFrame))

[[nan nan nan]
 [ 1.  1.  1.]
 [ 1.  1. nan]]
str --> 3 
col --> 3
Check NULL values in dataframe successfull result is True
Add column with indexes in dataframe successfull
[[nan nan nan nan]
 [ 0.  1.  1.  1.]
 [ 1.  1.  1. nan]]


In [7]:
print(GOOD_dataFrame)
print(prepData.add_col_indexes(GOOD_dataFrame))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
str --> 3 
col --> 3
Check NULL values in dataframe error
Add column with indexes in dataframe successfull
[[0. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 1. 1. 1.]]


#### delete_names

In [8]:
print(BAD_dataFrame)
print(prepData.delete_names(BAD_dataFrame))

[[nan nan nan]
 [ 1.  1.  1.]
 [ 1.  1. nan]]
Delete columns with names in dataframe successfull
[[ 1.  1.  1.]
 [ 1.  1. nan]]


In [9]:
print(GOOD_dataFrame)
print(prepData.delete_names(GOOD_dataFrame))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Delete columns with names in dataframe successfull
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### delete_nan_str

In [4]:
print(BAD_dataFrame)
print("res =\n", prepData.delete_nan_str(BAD_dataFrame))

[[nan nan nan]
 [ 1.  1.  1.]
 [ 1.  1. nan]]
str = 3
col = 3
Check NULL values in dataframe successfull result is True
Check NULL values in dataframe successfull result is False
res_dataFrame = [[0. 0. 0.]
 [1. 1. 1.]]
Check NULL values in dataframe successfull result is True
Delete NULL lines in dataframe successfull
res =
 [[1. 1. 1.]]


In [5]:
print(GOOD_dataFrame)
print("res =\n", prepData.delete_nan_str(GOOD_dataFrame))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
str = 3
col = 3
Check NULL values in dataframe successfull result is False
res_dataFrame = [[0. 0. 0.]
 [1. 1. 1.]]
Check NULL values in dataframe successfull result is False
res_dataFrame = [[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
Check NULL values in dataframe successfull result is False
res_dataFrame = [[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Delete NULL lines in dataframe successfull
res =
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### to_standardization_df

In [6]:
print(BAD_dataFrame)
print("res =\n", prepData.to_standardization_df(BAD_dataFrame))

[[nan nan nan]
 [ 1.  1.  1.]
 [ 1.  1. nan]]
str --> 3 
col --> 3
Check NULL values in dataframe successfull result is True
Add column with indexes in dataframe successfull
Delete columns with names in dataframe successfull
str = 2
col = 4
Check NULL values in dataframe successfull result is False
res_dataFrame = [[0. 0. 0. 0.]
 [0. 1. 1. 1.]]
Check NULL values in dataframe successfull result is True
Delete NULL lines in dataframe successfull
Standartization dataframe successfull
res =
 [[0. 1. 1. 1.]]


In [7]:
print(GOOD_dataFrame)
print("res =\n", prepData.to_standardization_df(GOOD_dataFrame))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
str --> 3 
col --> 3
Check NULL values in dataframe successfull result is False
Add column with indexes in dataframe successfull
Delete columns with names in dataframe successfull
str = 3
col = 4
Check NULL values in dataframe successfull result is False
res_dataFrame = [[0. 0. 0. 0.]
 [0. 1. 1. 1.]]
Check NULL values in dataframe successfull result is False
res_dataFrame = [[0. 0. 0. 0.]
 [0. 1. 1. 1.]
 [1. 1. 1. 1.]]
Check NULL values in dataframe successfull result is False
res_dataFrame = [[0. 0. 0. 0.]
 [0. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 1. 1. 1.]]
Delete NULL lines in dataframe successfull
Standartization dataframe successfull
res =
 [[0. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 1. 1. 1.]]


#### employ_Pipline

In [5]:
inp_dir = "C:/Users/Dmitriy/Desktop/Univer/Diplom/diplom_autoencoder/data/raw/tests"
out_dir = "C:/Users/Dmitriy/Desktop/Univer/Diplom/diplom_autoencoder/data/processed"

In [8]:
prepData.employ_Pipline(inp_dir,
                        out_dir,
                        prepData.defaultPipline)

Getting a list of documents...
   .../Small_BAD_test_FD001.csv
   .../Small_GOOD_test_FD001.csv
Documents have been received
  Processed -->  Small_BAD_test_FD001.csv
Check NULL values in dataframe successfull result is True
Dataset is BAD Starting standartization dataframe...
str --> 5 
col --> 4
Check NULL values in dataframe successfull result is True
Add column with indexes in dataframe successfull
Delete columns with names in dataframe successfull
str = 4
col = 5
Check NULL values in dataframe successfull result is True
Check NULL values in dataframe successfull result is False
res_dataFrame = [[ 0.0e+00  0.0e+00  0.0e+00  0.0e+00  0.0e+00]
 [ 1.0e+00  1.0e+00  2.0e+00 -2.7e-03 -3.0e-04]]
Check NULL values in dataframe successfull result is True
Check NULL values in dataframe successfull result is True
Delete NULL lines in dataframe successfull
Standartization dataframe successfull
Dataset is GOOD  Starting employ pipeline...
  Processed -->  Small_GOOD_test_FD001.csv
Check NULL v

True